version: '3.9'

services:
  pomodoro:
    image: pomodoro-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pomodoro.entrypoints=websecure"
      - "traefik.http.routers.pomodoro.rule=Host(`pomodoro.chbenjum.xyz`)"
      - "traefik.http.routers.pomodoro.tls.certresolver=letsencrypt"
    networks:
      - traefik

networks:
  traefik:
    external: true
